%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% BioMetric Data Representation   %
% April 2010 - Alessandro Savoia  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%SURFACE PATTERN RENDERING MODULE%%

close all
clc 
clear all
load data.mat

% Surface Pattern Rendering user interface 

% Plot of the x and y b-scans
set(0,'Units','pixels') 
scnsize = get(0,'ScreenSize');
bdwidth = 5;
topbdwidth = 70;

% box
pos_2d  = [1/3*scnsize(3) + bdwidth,... 
	1/3*scnsize(4) - 100 - topbdwidth,...
	scnsize(3)/2 - 2*bdwidth,...
	60];

pos2d_control = figure('Position',pos_2d,'Toolbar','none','Menubar','none');

% text and labels
uicontrol('Style', 'text',...
    'String','INTERPOLATION:',...
    'Position', [0/5*pos_2d(3) 2/3*pos_2d(4) 1/5*pos_2d(3) pos_2d(4)/3]);
uicontrol('Style', 'text',...
    'String','Axial step size = ',...
    'Position', [1/5*pos_2d(3) 2/3*pos_2d(4) 1/5*pos_2d(3) pos_2d(4)/3]);
uicontrol('Style', 'text',...
    'String','mm',...
    'Position', [2.6/5*pos_2d(3) 2/3*pos_2d(4) 0.4/5*pos_2d(3) pos_2d(4)/3]);
uicontrol('Style', 'text',...
    'String','k = ',...
    'Position', [3/5*pos_2d(3) 2/3*pos_2d(4) 0.5/5*pos_2d(3) pos_2d(4)/3]);


uicontrol('Style', 'text',...
    'String','SURFACE DETECTION:',...
    'Position', [0/5*pos_2d(3) 1/3*pos_2d(4) 1/5*pos_2d(3) pos_2d(4)/3]);
uicontrol('Style', 'text',...
    'String','Treshold (0 - 255) = ',...
    'Position', [1/5*pos_2d(3) 1/3*pos_2d(4) 1/5*pos_2d(3) pos_2d(4)/3]);
uicontrol('Style', 'text',...
    'String','Filter size (pixels) = ',...
    'Position', [2.6/5*pos_2d(3) 1/3*pos_2d(4) 0.8/5*pos_2d(3) pos_2d(4)/3]);

uicontrol('Style', 'text',...
    'String','RENDERING DEPTH:',...
    'Position', [0/5*pos_2d(3) 0/3*pos_2d(4) 1/5*pos_2d(3) pos_2d(4)/3]);
uicontrol('Style', 'text',...
    'String','mm',...
    'Position', [3.6/5*pos_2d(3) 0/3*pos_2d(4) 0.4/5*pos_2d(3) pos_2d(4)/3]);

% sliders
xslide_h = uicontrol('Style','slider',...
                     'Min',-max(Z)/2,'Max',max(Z)/2,...
                     'Value',0,...
                     'Position', [1/5*pos_2d(3) 0/3*pos_2d(4) 2/5*pos_2d(3) pos_2d(4)/3],...
                     'SliderStep',[(Z(2)-Z(1))/Z(length(Z)) 10*(Z(2)-Z(1))/Z(length(Z))],...
                     'Callback',' set(depth_h,''String'', num2str(get(xslide_h,''Value'') )) , update_pattern ');

% buttons
interp_h = uicontrol('Position',[4/5*pos_2d(3) 2/3*pos_2d(4) 1/5*pos_2d(3) pos_2d(4)/3],...
                    'String','Interpolate',...
                    'Callback','update_interp');
detect_h = uicontrol('Position',[4/5*pos_2d(3) 1/3*pos_2d(4) 1/5*pos_2d(3) pos_2d(4)/3],...
                    'String','Detect',...
                    'Callback','update_surfdetect');
update_h = uicontrol('Position',[4/5*pos_2d(3) 0/3*pos_2d(4) 1/5*pos_2d(3) pos_2d(4)/3],...
                    'String','Update',...
                    'Callback','update_pattern');


% data
axstep_h = uicontrol('Style', 'edit',...
    'String',num2str(Z(2)-Z(1)),...
    'Position', [2/5*pos_2d(3) 2/3*pos_2d(4) 0.5/5*pos_2d(3) pos_2d(4)/3] );
k_h = uicontrol('Style', 'edit',...
    'String',num2str(3),...
    'Position', [3.4/5*pos_2d(3) 2/3*pos_2d(4) 0.5/5*pos_2d(3) pos_2d(4)/3] );
tresh_h = uicontrol('Style', 'edit',...
    'String',num2str(64),...
    'Position', [2/5*pos_2d(3) 1/3*pos_2d(4) 0.5/5*pos_2d(3) pos_2d(4)/3] );
filter_h = uicontrol('Style', 'edit',...
    'String',num2str(20),...
    'Position', [3.4/5*pos_2d(3) 1/3*pos_2d(4) 0.5/5*pos_2d(3) pos_2d(4)/3] );
depth_h = uicontrol('Style', 'edit',...
    'String',num2str(0),...
    'Position', [3/5*pos_2d(3) 0/3*pos_2d(4) 0.5/5*pos_2d(3) pos_2d(4)/3] );

M = flipdim( M,2);
pattern=figure;

update_surfdetect;






